Branch
DingDDong/java-lotto pull request #1
Opened 2023-05-19 09:16 UTC by DingDDong

## Lotto 
기능 구현리스트와 순서도를 구상하는 과정에서 '오브젝트' 책에서 배운것 처럼 응집도를 높게, 결합도를 낮게 코드를 작성하고 싶었지만 너무 큰 욕심이였다고 생각이 들 정도로 많이 어려웠다. 사실 아직도 잘 모르겠어서 고민만 하다가 너무 지체되는것 같아 뭐라도 짜보자 라고 생각하고 시작했다. 아직 나는 능력이 많이 부족해서 저런 부분을 다 생각하면서 코드를 짜는게 어렵다고 느껴졌다. 그래서 우선 요구 사항에 맞게 작동되는 코드를 짜고나서 책임과 역할에 맞게 리팩토링 해야겠다고 생각했다. 
코드를 직접 만들어가며 느낀점은 일단 많이 보고 많이 쳐봐야 된다고 생각이 들었다. 생각만 많이 하고서는 아무것도 이뤄지지 않는다는 것이다. 어느정도의 구상과 생각은 필요하지만 너무 깊은 생각은 일을 진행하는데에 있어서 큰 방해가 된다는 것을 많이 느꼈다.

2023-05-20 06:04 UTC, Be-poz requested changes
현진 잘 확인했고 코멘트 확인하구 구현 나머지 마무리 다 하구 재요청줘~

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/controller/LottoController.java
> +    InputView inputView = new InputView();
일단 기본적으로 private final을 붙이고 생각하면 좋아

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/view/InputView.java
> +    }
enum으로 해도 되긴한데 일반적으로는 이런거는 그냥 상수로 두고 사용하는 편이야. enum은 종류를 나눌 수 있는 그런 경우에 쓰여. Fruit enum이 있으면 사과, 바나나, 오렌지 이런식

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/validator/MoneyValidator.java
> +        if ((Integer.parseInt(money)) == 0) {
음수체크도 하는게 좋아보이네   
-1000 이 통과된다

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/model/LottoStore.java
> +import java.util.List;
미사용 import는 삭제

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/model/LottoStore.java
> +    public LottoStore(int money){
변수하고 생성자는 중간에 개행을 넣어주자

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/model/LottoStore.java
> +import java.util.List;
<img width="837" alt="image" src="https://github.com/DingDDong/java-lotto/assets/45073750/d0371cb1-ba93-499c-befe-af4dc3da05b6">
 인텔리제이에서 commit 할 때때에 우측에 optimize import랑 reformat code를 체크해주면 커밋 직전에 알아서 해줘

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/model/LottoStore.java
> +    private final int LottoAmount;
변수는 카멜케이스로

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/controller/LottoController.java
> +        LottoStore lottoStore = new LottoStore(inputView.inputMoney());
로또 넘버는 그냥 로또 장수를 가지고 있는 클래스인게 다인데 사용자가 로또 몇 장의 로또 장수를 샀는지에 대한 정보를 LottoStore가 가져야 되는게 맞는걸까?

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/model/PlayerLottoNumbers.java
> +        return Stream.generate(PlayerLottoNumber::autoMakeLottoNumber).limit(lottoAmount).collect(Collectors.toList());
'.' 사용해서 체이닝할 때에는 개행을 해주자

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/model/PlayerLottoNumber.java
> +    }
그냥 생성자를 쓰면 되는데 밑의 정적 팩토리 메서드는 왜 생성해준거야?

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/model/PlayerLottoNumber.java
> +}
마지막에 개행

2023-05-20 06:04 UTC, Be-poz commented on src/main/java/lotto/util/ExceptionMessage.java
> +public enum ExceptionMessage {
이것 또한 예외 메세지의 상수 클래스를 두는 것과 고민됐을 것 같은데 이것으로 결정하게된 판단근거가 뭐야?

2023-05-20 06:04 UTC, Be-poz commented on readme.md
> +- 로또 번호의 숫자 범위는 1~45까지이다.분
ㅇ?

2023-05-20 06:04 UTC, Be-poz commented
pr 코멘트에는 이번 미션 느낀점 쓰지말고 이번 pr에 대한 설명을 써줘 어떤 기준으로 설계를 했다. 유의할 점, 질문 이런 것들

2023-05-22 06:17 UTC, DingDDong commented
> pr 코멘트에는 이번 미션 느낀점 쓰지말고 이번 pr에 대한 설명을 써줘 어떤 기준으로 설계를 했다. 유의할 점, 질문 이런 것들

아하 확인! 다음부턴 그런식으로 쓸게

2023-06-20 05:55 UTC, closed without merging